Add Ameba checks to CI and fix non-compliant code

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -4,5 +4,24 @@
 set -e
 set -o pipefail
 
-printf "\nrunning specs with 'crystal spec'\n\n"
+printf "\nChecking code formatting...\n\n"
+
+if ! crystal tool format --check src spec > /dev/null; then
+    printf "\nCode is not formatted.\n"
+    printf "\nFormat the code with: crystal tool format src spec\n\n"
+    exit 1
+else
+    printf "\nCrystal format checks passed.\n\n"
+fi
+
+if ! crystal ./bin/ameba.cr; then
+    printf "\nCode did not pass Ameba checks.\n"
+    printf "\nResolve Ameba linter errors, then run this checker again\n\n"
+    exit 1
+else
+    printf "\nAmeba linter checks passed.\n\n"
+fi
+
+printf "\nRunning specs with 'crystal spec'\n\n"
 crystal spec "$@"
+
